### ISSUE TITLE
COPYRIGHT NOTICE AGAINST THE TRADEMARK 'Sonny'

### ISSUE THREAD

**Issue by sonnyp** [felixmaier/sonnyJS#1]
just messing around :smile:

**Comment by felixmaier** [comment]
Hello,

Thanks for your notice, didn't checked if the name is already taken.

But SonnyJS isn't same like Sonny, right?

Please correct me if I'm wrong, I don't want to get in trouble..:)

Kind regards

>

**Comment by sonnyp** [comment]
@felixmaier sorry a friend of mind sent me a link to this repository I was just joking :)
